//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/Diego/Desktop/Fundamentos de software de sistemas/Practicas/02/QuintanillaEscalante_Practica03/SICXE.g by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SICXEParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ISICXEListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] SICXEParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] SICXEParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] SICXEParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] SICXEParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] SICXEParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] SICXEParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] SICXEParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] SICXEParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] SICXEParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] SICXEParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.extendedInstr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtendedInstr([NotNull] SICXEParser.ExtendedInstrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.extendedInstr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtendedInstr([NotNull] SICXEParser.ExtendedInstrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.f1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF1([NotNull] SICXEParser.F1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.f1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF1([NotNull] SICXEParser.F1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.f2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF2([NotNull] SICXEParser.F2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.f2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF2([NotNull] SICXEParser.F2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.f3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF3([NotNull] SICXEParser.F3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.f3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF3([NotNull] SICXEParser.F3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.f3Operands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterF3Operands([NotNull] SICXEParser.F3OperandsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.f3Operands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitF3Operands([NotNull] SICXEParser.F3OperandsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.simpleOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleOperand([NotNull] SICXEParser.SimpleOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.simpleOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleOperand([NotNull] SICXEParser.SimpleOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.indexedOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexedOperand([NotNull] SICXEParser.IndexedOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.indexedOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexedOperand([NotNull] SICXEParser.IndexedOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.immediateOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImmediateOperand([NotNull] SICXEParser.ImmediateOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.immediateOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImmediateOperand([NotNull] SICXEParser.ImmediateOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.indirectOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndirectOperand([NotNull] SICXEParser.IndirectOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.indirectOperand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndirectOperand([NotNull] SICXEParser.IndirectOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirective([NotNull] SICXEParser.DirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirective([NotNull] SICXEParser.DirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SICXEParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] SICXEParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SICXEParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] SICXEParser.ValueContext context);
}
