//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/Diego/Desktop/Fundamentos de software de sistemas/Practicas/02/QuintanillaEscalante_Practica03/SICXE.g by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class SICXEParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		PLUS=1, COMMA=2, HASH=3, AT=4, OPCODE_F1=5, OPCODE_F2=6, OPCODE_F3=7, 
		DIRECTIVE=8, REG=9, ID=10, NUMBER=11, HEX=12, CHAR_LITERAL=13, COMMENT=14, 
		NEWLINE=15, WS=16;
	public const int
		RULE_program = 0, RULE_line = 1, RULE_statement = 2, RULE_label = 3, RULE_instruction = 4, 
		RULE_extendedInstr = 5, RULE_f1 = 6, RULE_f2 = 7, RULE_f3 = 8, RULE_f3Operands = 9, 
		RULE_simpleOperand = 10, RULE_indexedOperand = 11, RULE_immediateOperand = 12, 
		RULE_indirectOperand = 13, RULE_directive = 14, RULE_value = 15;
	public static readonly string[] ruleNames = {
		"program", "line", "statement", "label", "instruction", "extendedInstr", 
		"f1", "f2", "f3", "f3Operands", "simpleOperand", "indexedOperand", "immediateOperand", 
		"indirectOperand", "directive", "value"
	};

	private static readonly string[] _LiteralNames = {
		null, "'+'", "','", "'#'", "'@'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "PLUS", "COMMA", "HASH", "AT", "OPCODE_F1", "OPCODE_F2", "OPCODE_F3", 
		"DIRECTIVE", "REG", "ID", "NUMBER", "HEX", "CHAR_LITERAL", "COMMENT", 
		"NEWLINE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SICXE.g"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static SICXEParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public SICXEParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public SICXEParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(SICXEParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 35;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 34274L) != 0)) {
				{
				{
				State = 32;
				line();
				}
				}
				State = 37;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 38;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEWLINE() { return GetToken(SICXEParser.NEWLINE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LabelContext label() {
			return GetRuleContext<LabelContext>(0);
		}
		public LineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_line; } }
	}

	[RuleVersion(0)]
	public LineContext line() {
		LineContext _localctx = new LineContext(Context, State);
		EnterRule(_localctx, 2, RULE_line);
		int _la;
		try {
			State = 47;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case PLUS:
			case OPCODE_F1:
			case OPCODE_F2:
			case OPCODE_F3:
			case DIRECTIVE:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 41;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==ID) {
					{
					State = 40;
					label();
					}
				}

				State = 43;
				statement();
				State = 44;
				Match(NEWLINE);
				}
				break;
			case NEWLINE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 46;
				Match(NEWLINE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExtendedInstrContext extendedInstr() {
			return GetRuleContext<ExtendedInstrContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public InstructionContext instruction() {
			return GetRuleContext<InstructionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DirectiveContext directive() {
			return GetRuleContext<DirectiveContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 4, RULE_statement);
		try {
			State = 52;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case PLUS:
				EnterOuterAlt(_localctx, 1);
				{
				State = 49;
				extendedInstr();
				}
				break;
			case OPCODE_F1:
			case OPCODE_F2:
			case OPCODE_F3:
				EnterOuterAlt(_localctx, 2);
				{
				State = 50;
				instruction();
				}
				break;
			case DIRECTIVE:
				EnterOuterAlt(_localctx, 3);
				{
				State = 51;
				directive();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LabelContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(SICXEParser.ID, 0); }
		public LabelContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_label; } }
	}

	[RuleVersion(0)]
	public LabelContext label() {
		LabelContext _localctx = new LabelContext(Context, State);
		EnterRule(_localctx, 6, RULE_label);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public F1Context f1() {
			return GetRuleContext<F1Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public F2Context f2() {
			return GetRuleContext<F2Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public F3Context f3() {
			return GetRuleContext<F3Context>(0);
		}
		public InstructionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction; } }
	}

	[RuleVersion(0)]
	public InstructionContext instruction() {
		InstructionContext _localctx = new InstructionContext(Context, State);
		EnterRule(_localctx, 8, RULE_instruction);
		try {
			State = 59;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case OPCODE_F1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 56;
				f1();
				}
				break;
			case OPCODE_F2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 57;
				f2();
				}
				break;
			case OPCODE_F3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 58;
				f3();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExtendedInstrContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(SICXEParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public F3Context f3() {
			return GetRuleContext<F3Context>(0);
		}
		public ExtendedInstrContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_extendedInstr; } }
	}

	[RuleVersion(0)]
	public ExtendedInstrContext extendedInstr() {
		ExtendedInstrContext _localctx = new ExtendedInstrContext(Context, State);
		EnterRule(_localctx, 10, RULE_extendedInstr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61;
			Match(PLUS);
			State = 62;
			f3();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class F1Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPCODE_F1() { return GetToken(SICXEParser.OPCODE_F1, 0); }
		public F1Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_f1; } }
	}

	[RuleVersion(0)]
	public F1Context f1() {
		F1Context _localctx = new F1Context(Context, State);
		EnterRule(_localctx, 12, RULE_f1);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 64;
			Match(OPCODE_F1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class F2Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPCODE_F2() { return GetToken(SICXEParser.OPCODE_F2, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] REG() { return GetTokens(SICXEParser.REG); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REG(int i) {
			return GetToken(SICXEParser.REG, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA() { return GetToken(SICXEParser.COMMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(SICXEParser.NUMBER, 0); }
		public F2Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_f2; } }
	}

	[RuleVersion(0)]
	public F2Context f2() {
		F2Context _localctx = new F2Context(Context, State);
		EnterRule(_localctx, 14, RULE_f2);
		try {
			State = 76;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 66;
				Match(OPCODE_F2);
				State = 67;
				Match(REG);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 68;
				Match(OPCODE_F2);
				State = 69;
				Match(REG);
				State = 70;
				Match(COMMA);
				State = 71;
				Match(REG);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 72;
				Match(OPCODE_F2);
				State = 73;
				Match(REG);
				State = 74;
				Match(COMMA);
				State = 75;
				Match(NUMBER);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class F3Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OPCODE_F3() { return GetToken(SICXEParser.OPCODE_F3, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public F3OperandsContext f3Operands() {
			return GetRuleContext<F3OperandsContext>(0);
		}
		public F3Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_f3; } }
	}

	[RuleVersion(0)]
	public F3Context f3() {
		F3Context _localctx = new F3Context(Context, State);
		EnterRule(_localctx, 16, RULE_f3);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78;
			Match(OPCODE_F3);
			State = 80;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 15384L) != 0)) {
				{
				State = 79;
				f3Operands();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class F3OperandsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SimpleOperandContext simpleOperand() {
			return GetRuleContext<SimpleOperandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IndexedOperandContext indexedOperand() {
			return GetRuleContext<IndexedOperandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ImmediateOperandContext immediateOperand() {
			return GetRuleContext<ImmediateOperandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IndirectOperandContext indirectOperand() {
			return GetRuleContext<IndirectOperandContext>(0);
		}
		public F3OperandsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_f3Operands; } }
	}

	[RuleVersion(0)]
	public F3OperandsContext f3Operands() {
		F3OperandsContext _localctx = new F3OperandsContext(Context, State);
		EnterRule(_localctx, 18, RULE_f3Operands);
		try {
			State = 86;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 82;
				simpleOperand();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 83;
				indexedOperand();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 84;
				immediateOperand();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 85;
				indirectOperand();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SimpleOperandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public SimpleOperandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simpleOperand; } }
	}

	[RuleVersion(0)]
	public SimpleOperandContext simpleOperand() {
		SimpleOperandContext _localctx = new SimpleOperandContext(Context, State);
		EnterRule(_localctx, 20, RULE_simpleOperand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 88;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IndexedOperandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA() { return GetToken(SICXEParser.COMMA, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REG() { return GetToken(SICXEParser.REG, 0); }
		public IndexedOperandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_indexedOperand; } }
	}

	[RuleVersion(0)]
	public IndexedOperandContext indexedOperand() {
		IndexedOperandContext _localctx = new IndexedOperandContext(Context, State);
		EnterRule(_localctx, 22, RULE_indexedOperand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90;
			value();
			State = 91;
			Match(COMMA);
			State = 92;
			Match(REG);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ImmediateOperandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HASH() { return GetToken(SICXEParser.HASH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public ImmediateOperandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_immediateOperand; } }
	}

	[RuleVersion(0)]
	public ImmediateOperandContext immediateOperand() {
		ImmediateOperandContext _localctx = new ImmediateOperandContext(Context, State);
		EnterRule(_localctx, 24, RULE_immediateOperand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 94;
			Match(HASH);
			State = 95;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IndirectOperandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AT() { return GetToken(SICXEParser.AT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public IndirectOperandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_indirectOperand; } }
	}

	[RuleVersion(0)]
	public IndirectOperandContext indirectOperand() {
		IndirectOperandContext _localctx = new IndirectOperandContext(Context, State);
		EnterRule(_localctx, 26, RULE_indirectOperand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97;
			Match(AT);
			State = 98;
			value();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DirectiveContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIRECTIVE() { return GetToken(SICXEParser.DIRECTIVE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value() {
			return GetRuleContext<ValueContext>(0);
		}
		public DirectiveContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_directive; } }
	}

	[RuleVersion(0)]
	public DirectiveContext directive() {
		DirectiveContext _localctx = new DirectiveContext(Context, State);
		EnterRule(_localctx, 28, RULE_directive);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			Match(DIRECTIVE);
			State = 102;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 15360L) != 0)) {
				{
				State = 101;
				value();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(SICXEParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(SICXEParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HEX() { return GetToken(SICXEParser.HEX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHAR_LITERAL() { return GetToken(SICXEParser.CHAR_LITERAL, 0); }
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 30, RULE_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 15360L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,16,107,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,1,0,5,0,34,8,0,10,0,12,0,37,9,0,1,0,1,0,1,1,3,1,42,8,1,1,1,1,
		1,1,1,1,1,3,1,48,8,1,1,2,1,2,1,2,3,2,53,8,2,1,3,1,3,1,4,1,4,1,4,3,4,60,
		8,4,1,5,1,5,1,5,1,6,1,6,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,3,7,77,
		8,7,1,8,1,8,3,8,81,8,8,1,9,1,9,1,9,1,9,3,9,87,8,9,1,10,1,10,1,11,1,11,
		1,11,1,11,1,12,1,12,1,12,1,13,1,13,1,13,1,14,1,14,3,14,103,8,14,1,15,1,
		15,1,15,0,0,16,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,0,1,1,0,10,13,
		104,0,35,1,0,0,0,2,47,1,0,0,0,4,52,1,0,0,0,6,54,1,0,0,0,8,59,1,0,0,0,10,
		61,1,0,0,0,12,64,1,0,0,0,14,76,1,0,0,0,16,78,1,0,0,0,18,86,1,0,0,0,20,
		88,1,0,0,0,22,90,1,0,0,0,24,94,1,0,0,0,26,97,1,0,0,0,28,100,1,0,0,0,30,
		104,1,0,0,0,32,34,3,2,1,0,33,32,1,0,0,0,34,37,1,0,0,0,35,33,1,0,0,0,35,
		36,1,0,0,0,36,38,1,0,0,0,37,35,1,0,0,0,38,39,5,0,0,1,39,1,1,0,0,0,40,42,
		3,6,3,0,41,40,1,0,0,0,41,42,1,0,0,0,42,43,1,0,0,0,43,44,3,4,2,0,44,45,
		5,15,0,0,45,48,1,0,0,0,46,48,5,15,0,0,47,41,1,0,0,0,47,46,1,0,0,0,48,3,
		1,0,0,0,49,53,3,10,5,0,50,53,3,8,4,0,51,53,3,28,14,0,52,49,1,0,0,0,52,
		50,1,0,0,0,52,51,1,0,0,0,53,5,1,0,0,0,54,55,5,10,0,0,55,7,1,0,0,0,56,60,
		3,12,6,0,57,60,3,14,7,0,58,60,3,16,8,0,59,56,1,0,0,0,59,57,1,0,0,0,59,
		58,1,0,0,0,60,9,1,0,0,0,61,62,5,1,0,0,62,63,3,16,8,0,63,11,1,0,0,0,64,
		65,5,5,0,0,65,13,1,0,0,0,66,67,5,6,0,0,67,77,5,9,0,0,68,69,5,6,0,0,69,
		70,5,9,0,0,70,71,5,2,0,0,71,77,5,9,0,0,72,73,5,6,0,0,73,74,5,9,0,0,74,
		75,5,2,0,0,75,77,5,11,0,0,76,66,1,0,0,0,76,68,1,0,0,0,76,72,1,0,0,0,77,
		15,1,0,0,0,78,80,5,7,0,0,79,81,3,18,9,0,80,79,1,0,0,0,80,81,1,0,0,0,81,
		17,1,0,0,0,82,87,3,20,10,0,83,87,3,22,11,0,84,87,3,24,12,0,85,87,3,26,
		13,0,86,82,1,0,0,0,86,83,1,0,0,0,86,84,1,0,0,0,86,85,1,0,0,0,87,19,1,0,
		0,0,88,89,3,30,15,0,89,21,1,0,0,0,90,91,3,30,15,0,91,92,5,2,0,0,92,93,
		5,9,0,0,93,23,1,0,0,0,94,95,5,3,0,0,95,96,3,30,15,0,96,25,1,0,0,0,97,98,
		5,4,0,0,98,99,3,30,15,0,99,27,1,0,0,0,100,102,5,8,0,0,101,103,3,30,15,
		0,102,101,1,0,0,0,102,103,1,0,0,0,103,29,1,0,0,0,104,105,7,0,0,0,105,31,
		1,0,0,0,9,35,41,47,52,59,76,80,86,102
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
